config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get '/auth/github', as: :github_login

  get '/auth/github/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/dashboard', to: 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/github_follow.rb
class GithubFollow
  attr_reader :login, :image, :url, :company, :bio, :name, :location
  def initialize(attributes={})
    @login    = attributes[:login]
    @image    = attributes[:avatar_url]
    @url      = attributes[:url]
    @company  = attributes[:company]
    @bio      = attributes[:bio]
    @name     = attributes[:name]
    @location = attributes[:location]
  end

  def self.get_followers(token)
    GithubService.new(token).followers.map do |raw_repo|
      GithubFollow.new(raw_repo)
    end
  end

  def self.get_following(token)
    GithubService.new(token).following.map do |raw_repo|
      GithubFollow.new(raw_repo)
    end
  end
end

app/models/github_repo.rb
class GithubRepo
  attr_reader :name, :description, :forks_count, :description, :language, 
              :updated, :stargazers_count, :stargazers_url, :url, :forks_url

  def initialize(attributes = {})
    @name              = attributes[:name]
    @description       = attributes[:description]
    @language          = attributes[:language]
    @updated           = attributes[:updated_at]
    @repo_url          = attributes[:url]
    @stargazers_count  = attributes[:stargazers_count]
    @stargazers_url    = attributes[:stargazers_url]
    @forks_count       = attributes[:forks_count]
    @forks_url         = attributes[:forks_url]
  end

  def self.get_repos(token)
    GithubService.new(token).repos.map do |raw_repo|
      GithubRepo.new(raw_repo)
    end
  end

  def self.get_starred_repos(token)
    GithubService.new(token).starred.map do |raw_repo|
      GithubRepo.new(raw_repo)
    end
  end
end

app/models/github_user.rb
class GithubUser
  attr_reader :image, :name, :login, :company, :location, :email, :blog, :joined

  def initialize(attributes={})
    @image    = attributes[:avatar_url]
    @name     = attributes[:name]
    @login    = attributes[:login]
    @company  = attributes[:company]
    @location = attributes[:location]
    @email    = attributes[:email]
    @blog     = attributes[:blog]
    @joined   = attributes[:created_at]
  end
  
  def self.get_user_data(token)
    data = GithubService.new(token).user_data
    GithubUser.new(data)
  end
end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth)
    user = User.find_or_create_by(uid: auth['uid'])
    user.uid      = auth['uid']
    user.token    = auth['credentials']['token']
    user.save
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @user = GithubUser.get_user_data(current_user.token)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env['omniauth.auth'])
      session[:user_id] = user.id
      redirect_to dashboard_path
    else
      redirect_to root_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<div class="custom-container main">
  <div class="col-md-3 left">
    <%= image_tag(@user.image, height: '230',  width: '229', class: 'avatar') %>
    <%= @user.name %>
    <%= @user.login %>
  </div>

  <div class="col-md-9 right">
    <div>

      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#overview" aria-controls="overview" role="tab" data-toggle="tab">Overview</a></li>
        <li role="presentation"><a href="#repos" aria-controls="repositories" role="tab" data-toggle="tab">Repositories</a></li>
        <li role="presentation"><a href="#stars" aria-controls="stars" role="tab" data-toggle="tab">Stars</a></li>
        <li role="presentation"><a href="#followers" aria-controls="followers" role="tab" data-toggle="tab">Followers</a></li>
        <li role="presentation"><a href="#following" aria-controls="following" role="tab" data-toggle="tab">Following</a></li>
      </ul>

      <!-- Tab panes -->
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="overview">
          overview
        </div>

        <div role="tabpanel" class="tab-pane" id="repositories">
          repos
        </div>

        <div role="tabpanel" class="tab-pane" id="stars">
          stars
        </div>

        <div role="tabpanel" class="tab-pane" id="followers">
          followers
        </div>

        <div role="tabpanel" class="tab-pane" id="following">
          following
        </div>
      </div>

    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= link_to "Login with Github", github_login_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apicurious</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= render partial: 'shared/post_navbar' %>
    <% else %>
      <%= render partial: 'shared/pre_navbar' %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_post_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= image_tag('mark-github.svg', size: 28) %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search GitHub">
        </div>
      </form>
      <ul class="nav navbar-nav">
        <li><a href="#">Pull requests</a></li>
      </ul>
      <ul class="nav navbar-nav">
        <li><a href="#">Issues</a></li>
      </ul>
      <ul class="nav navbar-nav">
        <li><a href="#">Gist</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= image_tag("plus.svg") %>  <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">New repository</a></li>
            <li><a href="#">Import repository</a></li>
            <li><a href="#">New gist</a></li>
            <li><a href="#">New organization</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <!-- put the user image here size: 20 -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= image_tag(@user.image, size: 20) %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li class="dropdown-logged-in-notice">Signed in as <%= @user.name %></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Your profile</a></li>
            <li><a href="#">Your stars</a></li>
            <li><a href="#">Explore</a></li>
            <li><a href="#">Integrations</a></li>
            <li><a href="#">Help</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Settings</a></li>
            <li><%= link_to "Sign out", logout_path, method: :delete %></a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_side_profile.html.erb
<div class="custom-container main">
  <div class="col-md-3 left">
    <%= image_tag(@user.image, height: '230',  width: '229', class: 'avatar') %>
    <%= @user.name %>
    <%= @user.login %>
  </div>

  <div class="col-md-9 right">
    <div>
      <ul class="nav nav-tabs">
        <li role="presentation" class="active"><a href="#">Overview</a></li>
        <li role="presentation"><a href="#">Respositories</a></li>
        <li role="presentation"><a href="#">Stars</a></li>
        <li role="presentation"><a href="#">Followers</a></li>
        <li role="presentation"><a href="#">Following</a></li>
      </ul>
    </div>
  </div>
</div>